# Makefile for assignment template
# Date: 2025
# Author: Daniel Montrallo Flickinger, PhD ; dflickinger@wpi.edu

assignment_name = RBE_assignment_template
export assignment_name

include /usr/local/share/RBEassignment/assignment_builder.mk
