
services:
  assBuild:
    build: .
    image: rbe550-assignment-builder
    volumes:
      - source:/source
      - output:/output
      - bib:/bib

volumes:
  - source: /work/RBE550/source
  - output: /work/RBE550/output
  - bib: /work/RBE550/bib
