services:
  assBuild:
    build: .
    image: rbe550-assignment-builder
    volumes:
      - source:/source
      - output:/output
      - bib:/bib

volumes:
  source:
    external: true
  output:
    external: true
  bib:
    external: true
